### ISSUE TITLE
Add dependencies of YARP on eigen when YARP 2.3.68 is released

### ISSUE THREAD

**Issue by traversaro** [robotology/homebrew-cask#4]
Required in YARP since 2.3.67.3 , see https://github.com/robotology/yarp/pull/896 .

cc @francesco-romano

**Comment by francesco-romano** [comment]
@traversaro  at the current state the yarp formula allows to install only stable versions, i.e. either released (2.3.66 right now) or the last version pointed by the master.

When the GSL/eigen stuff will be merged into master?

**Comment by traversaro** [comment]
Eigen support I hope that will be merged in `devel` in the next days. `devel` will be merged in `master`  when we will do the 2.3.68 release. I modified the title accordingly.

**Comment by francesco-romano** [comment]
Done in https://github.com/robotology/homebrew-cask/commit/1417abac94cd4409f6a1d5bcae99abb12215c271
